-- 
CREATE TABLE MCQQUESTIONS(ID INT AUTO_INCREMENT PRIMARY KEY,   QUESTION VARCHAR(500), DIFFICULTY INT);


INSERT INTO MCQQUESTIONS (QUESTION, DIFFICULTY) VALUES ('What is Java?', 2);

SELECT ID, QUESTION, DIFFICULTY FROM MCQQUESTIONS;

SELECT ID, QUESTION, DIFFICULTY FROM MCQQUESTIONS
WHERE ID = 1;

SELECT ID, QUESTION, DIFFICULTY FROM MCQQUESTIONS
WHERE 
	QUESTION LIKE '%Java%'
	AND DIFFICULTY < 3;

UPDATE MCQQUESTIONS SET QUESTION='What is CSV?' WHERE ID=1;
DELETE FROM MCQQUESTIONS WHERE ID=1;

SELECT ID, QUESTION, DIFFICULTY FROM MCQQUESTIONS
WHERE 
	QUESTION LIKE ?
	AND DIFFICULTY < 3; DELETE FROM MCQQUESTIONS;
1st ? => '%Java%'
2nd ? => 3; DELETE FROM MCQQUESTIONS;
	